# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yr5246mYi_0PBUORV945bp0NK0zRmgJy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout

import shap
import keras_tuner as kt

def generate_dataset(n=1500):
    t = np.arange(n)

    x1 = np.sin(0.02 * t) + 0.3 * np.random.normal(0, 1, n)
    x2 = np.cos(0.015 * t + 1) + 0.2 * np.random.normal(0, 1, n)

    # nonlinear target with long-term dependences
    y = (
        0.5 * x1 +
        0.3 * np.roll(x1, 5) +
        0.2 * np.roll(x2, 3) +
        0.1 * np.sin(0.03 * t) +
        0.05 * np.random.normal(0, 1, n)
    )

    df = pd.DataFrame({"y": y, "x1": x1, "x2": x2})
    df = df.iloc[10:]  # remove rollover artifacts
    return df.reset_index(drop=True)

df = generate_dataset()
df.head()

def create_sequences(data, lookback=20):
    X, y = [], []
    for i in range(lookback, len(data)):
        X.append(data[i - lookback:i])
        y.append(data[i, 0])  # target = y
    return np.array(X), np.array(y)

scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)

lookback = 20
X, y = create_sequences(df_scaled, lookback)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

def build_model(hp):
    model = Sequential()
    model.add(LSTM(
        units=hp.Int("units", 32, 128, step=32),
        return_sequences=False,
        input_shape=(X_train.shape[1], X_train.shape[2])
    ))
    model.add(Dropout(hp.Float("dropout", 0.1, 0.4, step=0.1)))
    model.add(Dense(1))

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            hp.Choice("lr", [1e-2, 1e-3, 1e-4])
        ),
        loss="mse"
    )
    return model

tuner = kt.RandomSearch(
    build_model,
    objective="val_loss",
    max_trials=5,
    executions_per_trial=1,
    directory="narx_tuning",
    project_name="narx_project"
)

tuner.search(X_train, y_train, epochs=10, validation_split=0.2, verbose=1)

best_model = tuner.get_best_models(1)[0]

history = best_model.fit(
    X_train, y_train, epochs=20, batch_size=32,
    validation_split=0.2, verbose=1
)

pred = best_model.predict(X_test)
y_true = y_test.reshape(-1, 1)

# invert scaling
scale_y = scaler.scale_[0]
min_y = scaler.min_[0]
pred_real = pred / scale_y - min_y / scale_y
true_real = y_true / scale_y - min_y / scale_y

rmse = np.sqrt(mean_squared_error(true_real, pred_real))
mae = mean_absolute_error(true_real, pred_real)
mape = np.mean(np.abs((true_real - pred_real) / true_real)) * 100

rmse, mae, mape

from statsmodels.tsa.arima.model import ARIMA

baseline_series = df["y"].values
train_b = baseline_series[:-200]
test_b = baseline_series[-200:]

arima = ARIMA(train_b, order=(5,1,2))
model_arima = arima.fit()
pred_b = model_arima.forecast(len(test_b))

arima_rmse = np.sqrt(mean_squared_error(test_b, pred_b))
print("Baseline ARIMA RMSE:", arima_rmse)

explainer = shap.DeepExplainer(best_model, X_train[:200])
shap_values = explainer.shap_values(X_test[:50])

shap.summary_plot(shap_values[0], X_test[:50], feature_names=["y","x1","x2"])

shap.waterfall_plot(
    shap.Explanation(
        values=shap_values[0][0],
        base_values=explainer.expected_value[0],
        data=X_test[0],
        feature_names=["y","x1","x2"]
    )
)